#!/bin/sh
# 
# This script does a rebase pull on this repo and sub repos.
# It will also clone sub repos that have not been cloned yet.
#
cd $(dirname $0)/..
for gitdir in $(find . -name ".git"); do
	path=$(dirname $gitdir)
	cd $path && git pull --rebase origin master
	cd -
done
for subrepo in $(find . -name ".subrepo"); do
	path=$(dirname $subrepo)
	if [ ! -d "$path/.git" ]; then
		repo=$(cat $subrepo)
		rm -rf $subrepo
		git clone $repo $path
	fi
done