#!/bin/sh
# 
# This script runs `make build` on anything in the project
# that has a Makefile with a build target defined. 
#
# Then it runs `docker build` on anything in the project with
# Dockerfile, using the directory as the image name using the
# flynn namespace. (ie: flynn/etcd)
#
set -e
cd $(dirname $0)/../..
for makefile in $(grep -lrI --exclude-dir=.go build: . | grep Makefile); do
	path=$(dirname $makefile)
	echo "\033[32m Building $(basename $path)... \033[39m"
	cd $path && make build
	cd - > /dev/null
done
for dockerfile in $(find . -not -path "\./\.*" -name "Dockerfile"); do
	path=$(dirname $dockerfile)
	echo "\033[32m Building container flynn/$(basename $path)... \033[39m"
	cd $path && docker build -t flynn/$(basename $path) .
	cd - > /dev/null
done