#!/bin/sh
# 
# This script runs `make build` on anything in the project
# that has a Makefile with a build target defined. 
#
# Then it runs `make install` on projects that implement it.
#
# Then it runs `docker build` on anything in the project with
# Dockerfile, using the directory as the image name using the
# flynn namespace. (ie: flynn/etcd)
#
set -e
cd $(dirname $0)/../..
for makefile in $(find . -not -path "\./\.*" -name "Makefile" -exec grep "build:" {} \; -print | grep Makefile); do
	path=$(dirname $makefile)
	echo "\033[32mBuilding $(basename $path)... \033[39m"
	cd $path && make build
	cd - > /dev/null
done
for makefile in $(find . -not -path "\./\.*" -name "Makefile" -exec grep "install:" {} \; -print | grep Makefile); do
	path=$(dirname $makefile)
	echo "\033[32mInstalling $(basename $path)... \033[39m"
	cd $path && make install
	cd - > /dev/null
done
for dockerfile in $(find . -not -path "\./\.*" -name "Dockerfile"); do
	path=$(dirname $dockerfile)
	echo "\033[32mBuilding container flynn/$(basename $path)... \033[39m"
	cd $path && docker build -t flynn/$(basename $path) .
	cd - > /dev/null
done